### ISSUE TITLE
Configure Raspberry Pi as Webserver

### ISSUE THREAD

**Issue by teamrocket77** [KSU-Google-DSC/Webapp#10]
## Overview

Configure a Raspberry PI to act as a Private Web Server for hosting the KSU-Google-DSC WebApp. 

**Intended Outcome**

Webapp should be accessible from the internet

## Blockers
- [ ] Possible router security we should ensure that we are following best practices for something hosted in the DMZ

## Features

- [ ] Ensure that application builds and run on Linux
- [ ] SSH access

## Future Ideas

- [ ] Webapp should be able to reboot after selecting an option in the Dashboard

**Comment by Sanjay-B** [comment]
Not feasible due to no open ports on campus. Backlogging until this becomes possible. Deployment will be on GCP.
