### ISSUE TITLE
Setup Database for Credentials

### ISSUE THREAD

**Issue by teamrocket77** [KSU-Google-DSC/Webapp#11]
## Overview
This aims to allow for secure, authenticated pulling of information from our database (security) to our web app through an automated deployment pipeline.

**Intended Outcome**
Integrated Credentials to be able to be pulled to our production web app. 

## Blockers
n/a

## Features
- [x] Create the Database (Google Cloudstore)
- [x] Create Authentication (Give Access to SDS Team)
- [x] Create Table for Authentication (Table, Attributes, etc)
- [x] Restrict Access unless Authenticated (Permission / Rules)
- [x] Add Credential Keys (Key-Value Pairs)

## Future Ideas
n/a

## References
n/a

**Comment by Sanjay-B** [comment]
Update: Next-Auth firebase adapter does not have compatibility for production rules and therefore, our authentication cannot be pushed mainline until that happens. I reached out to the OSS team that maintains the project and I pushed up some changes to further the conversation. I will update on progress soon. marking this as blocked until further notice. @teamrocket77
