### ISSUE TITLE
Team Design Page

### ISSUE THREAD

**Issue by Sanjay-B** [KSU-Google-DSC/Webapp#13]
## Overview

This page is supposed to showcase all of our team members. Each team member should be able to connect social media to their profiles. Full name, roles and department should be listed for each team member. 

The design should be simple but, should also be Googly.

Use [Material Ui](https://mui.com/material-ui/) Design.

**Intended Outcome**

Team page should be material ui, should look nice and fit the rest of the pages. 

## Blockers

- [x] Landing Design Page (https://github.com/KSU-Google-DSC/Webapp/issues/16)

## Features

- [x] Display Team Role for Each Team Member
- [x] Display Full Name for Each Team Member
- [x] Display Team Department for Each Team Member
- [x] Display Social Media for Each team Member

## Future Ideas

n/a

**Comment by aimiisme** [comment]
@Sanjay-B In ```Team``` tab, who should be included in the core team section? Is it better to divide the core team section into multiple distinct rows for each department?

**Comment by Sanjay-B** [comment]
@aimiisme I think it's best to have everyone on the team in the core team section. First leadership and then, the rest of the team.

**Comment by Sanjay-B** [comment]
Approved by @Sanjay-B . Considering the design to be complete. You can reopen if need-be.
