### ISSUE TITLE
Events Design Page

### ISSUE THREAD

**Issue by Sanjay-B** [KSU-Google-DSC/Webapp#14]
## Overview

This page is supposed to display in a grid-like fashion all of our events. Cards should have the title, date, and a way to add it to their calendar. When the user's mouse hovers over the card, the description will be shown. 

The design should be simple but, should also be Googly.

Use [Material Ui](https://mui.com/material-ui/) Design.

**Intended Outcome**

Events page should be material ui, should look nice and fit the rest of the pages. 

## Blockers

- [ ] Landing Design Page (https://github.com/KSU-Google-DSC/Webapp/issues/16)

## Features

- [x] Cards should have a title 
- [x] Cards should have a date
- [x] Cards should have a description
- [x] Mouse hover should show the description
- [x] A button or icon to add event date to calendar

## Future Ideas

n/a

**Comment by aimiisme** [comment]
@Sanjay-B Please review the Event page design on Adobe XD so I can start working on it

**Comment by Sanjay-B** [comment]
Approved by @Sanjay-B . Considering the design to be complete. You can reopen if need-be.
