### ISSUE TITLE
Landing Design Page

### ISSUE THREAD

**Issue by Sanjay-B** [KSU-Google-DSC/Webapp#16]
## Overview

This page is supposed to act as the landing page (i.e the root page of the site or the first page the user will go to).

The design should be simple but, should also be Googly.

Use [Material Ui](https://mui.com/material-ui/) Design.

**Intended Outcome**

Landing page should be material ui, should look nice and fit the rest of the pages. 

## Blockers

n/a

## Features

- [x] Responsive Navbar (DSC KSU (left) & About, Events, Socials, Our Team, Login (right))
- [x] Google Developer Student Club w/ Kennesaw State University Text (middle)
- [x] "Get Started" Button (points to ``/about``)
- [x] Anything else to make the page look nice

## Future Ideas

n/a

**Comment by aimiisme** [comment]
Hi Sanjay, you mentioned that the navigation bar also has /social tab but you didn't mention how it look like. I assume that it will have our Instagram, Twitter and Discord links. Instead of making the whole separate /social tab, why don't we put it under /about tab or /OurTeam tab?

**Comment by Sanjay-B** [comment]
@aimiisme ``/socials`` acts as a linktree so that it's easy to share all of our social medias on one page instead of scrolling down. Eventually, there will be a QR code that points to ``/socials``.

As for design, keep it consistent with everything else but, outside of that.. have fun with it!

**Comment by Sanjay-B** [comment]
Approved by @Sanjay-B . Considering the design to be complete. You can reopen if need-be.
