### ISSUE TITLE
Recruitment Webpage UI Design

### ISSUE THREAD

**Issue by theTechOwl** [KSU-Google-DSC/Webapp#23]
Design the recruitment page for students willing to join the KSU Google DSC. 
## Features
The design must cover the following:
- [x] A recruitment page encouraging students to join the organization. There must be a link to the form
- [x] A custom-made recruitment form. Its content must follow the format of the existing "recruitment" Google Forms document.

**Comment by Sanjay-B** [comment]
Approved by @Sanjay-B . Considering the design to be complete. You can reopen if need-be.
