### ISSUE TITLE
Bug: Wave Animation Infinitely causes Horizontal Scroll

### ISSUE THREAD

**Issue by Sanjay-B** [KSU-Google-DSC/Webapp#31]
When going to the landing page (`/`), the wave animation causes an infinite horizontal scroll in branch (https://github.com/KSU-Google-DSC/Webapp/tree/feature/wave_animation),

Repro:
`git checkout feature/wave_animation`

`npm run dev`

Going to http://localhost:3000/ in a web browser.

**Comment by Sanjay-B** [comment]
Currently blocks merging https://github.com/KSU-Google-DSC/Webapp/pull/27 into `dev` branch.

**Comment by aimiisme** [comment]
@Sanjay-B I have resolved the bug, however, merge conflicts occurred when I tried to push changes to remote branch

**Comment by PremKSU** [comment]
Can you force push the bugfix to another remote branch?

**Comment by aimiisme** [comment]
@Sanjay-B @PremKSU Resolve this issue with a new pull request #32

**Comment by Sanjay-B** [comment]
Reviewing https://github.com/KSU-Google-DSC/Webapp/pull/32 . @aimiisme

**Comment by Sanjay-B** [comment]
Fixed as of https://github.com/KSU-Google-DSC/Webapp/pull/32 . Closing. cc: @PremKSU
