### ISSUE TITLE
Linking href in Drawer Component

### ISSUE THREAD

**Issue by aimiisme** [KSU-Google-DSC/Webapp#41]
- [ ]  Link the page href properly in drawer component (drawer navbar) + Login/Logout button in DrawerComp for mobile user
- [x] Link the DSC logo to homepage.
- [x] Link `Get Started` button in homepage to `about` page

**Comment by aimiisme** [comment]
@Sanjay-B Hey Sanjay, I think we forgot to link the button in drawer component (which is the navbar for mobile user). I have tried to do the same way as you did in `navbar.js` but it didn't work. We also need `Login`/`Logout` button in the drawer component as well.

**Comment by Sanjay-B** [comment]
> @Sanjay-B Hey Sanjay, I think we forgot to link the button in drawer component (which is the navbar for mobile user). I have tried to do the same way as you did in `navbar.js` but it didn't work. We also need `Login`/`Logout` button in the drawer component as well.

I will get this done today. I disabled authentication site-wide because it was causing issues. I reached out to the Next-Auth team to push up some changes to them that would allow us to use it in production. @aimiisme

**Comment by Sanjay-B** [comment]
Closing. Merged as of https://github.com/KSU-Google-DSC/Webapp/pull/43. Login href linking will come when Oauth makes it's way to a release candidate. cc: @PremKSU
