### ISSUE TITLE
Warning: Expected Server HTML to contain a matching <a> in <a>

### ISSUE THREAD

**Issue by Sanjay-B** [KSU-Google-DSC/Webapp#46]
![image](https://user-images.githubusercontent.com/22083307/196618024-b3a0b842-201e-4725-8528-8adaf2a3ca7a.png)

Repro: 
``npm run dev``
Go to ``http://localhost:3000``.
Look at browser console via F12.

**Comment by Sanjay-B** [comment]
cc: @PremKSU

**Comment by aimiisme** [comment]
A PR #55 has been made to resolve this issue. Awaiting for code review
