### ISSUE TITLE
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>

### ISSUE THREAD

**Issue by Sanjay-B** [KSU-Google-DSC/Webapp#47]
![image](https://user-images.githubusercontent.com/22083307/196618535-a78f3c1c-700e-4573-8a16-4eeeb847a80d.png)

Repro: 
``npm run dev``
Go to ``http://localhost:3000``.
Look at browser console via F12.

**Comment by Sanjay-B** [comment]
cc: @PremKSU

**Comment by aimiisme** [comment]
A PR #55 has been made to resolve this issue. Awaiting for code review
