### ISSUE TITLE
MUI: The `value` provided to the Tabs component is invalid. None of the Tabs' children match with "undefined". You can provide one of the following values: 0, 1, 2, 3, 4.

### ISSUE THREAD

**Issue by Sanjay-B** [KSU-Google-DSC/Webapp#48]
![image](https://user-images.githubusercontent.com/22083307/196619086-cb52d0e4-5ea0-4c0f-bf5c-39e00c07e1a1.png)

Repro: 
``npm run dev``
Go to ``http://localhost:3000``.
Look at browser console via F12.

**Comment by Sanjay-B** [comment]
cc: @PremKSU

**Comment by aimiisme** [comment]
A PR #55 has been made to resolve this issue. Awaiting for code review
