### ISSUE TITLE
Environment Variables do not mirror to Process.env

### ISSUE THREAD

**Issue by Sanjay-B** [KSU-Google-DSC/Webapp#52]
Weird behavior with GitHub actions where environment variables do not translate correctly to process.env (nodejs). This currently breaks production build (RC0) integrity because certain keys turn up as empty which causes panic. Build then, begins to fail and aborts.

**Comment by Sanjay-B** [comment]
Ongoing investigation. Attempting a feasible solution. Eat: ~1 - 2 days. Cc: @PremKSU

**Comment by teamrocket77** [comment]
What about pushing the variables directly into the GCR console?
@Sanjay-B

**Comment by Sanjay-B** [comment]
> What about pushing the variables directly into the GCR console? @Sanjay-B

I rather leverage Github Action Secrets because, it's easier to track later on (if the size of keys magically grows) & it's easier in terms of overall setup (which will help with adoption). @teamrocket77

**Comment by Sanjay-B** [comment]
Fixed as of https://github.com/KSU-Google-DSC/Webapp/commit/f5e5b19eeaed30d610934356aec1204154fc252c . cc: @teamrocket77
